import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/app/Context/AuthContext";
import { TradeProvider } from "@/app/Context/TradeContext";
import { PriceProvider } from "./Context/PriceProvider";

export const metadata: Metadata = {
  title: "TREADING ELEVEN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="App bg-black-700">
        <AuthProvider>
          <PriceProvider>
            <TradeProvider>{children}</TradeProvider>
          </PriceProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
