
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/Context/AuthContext";
import { TradeProvider } from "@/Context/TradeContext";

export const metadata: Metadata = {
  title: "TREADING ELEVEN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="App bg-black-700">
        <AuthProvider>
          <TradeProvider>
            {children}
          </TradeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}